### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Carter907** [SirOphis/jscheduler#2]
I was thinking of adding some documentation to the model based on a global documentation style. I wanted to pick something that was verbose so that we could pick it apart down to a level that was suitable for this scale of project. This is the kind of layout I had in mind:

**constructors**
>list~
- the type of constructor (no-args), (all-args) or similar
- the params using `@param`
- any throws clauses using `@throws`
- any important methods that are used with `@see`

**methods**
>list~
- small description describing it's purpose
- the params using `@param`
- any throws clauses using `@throws`
- any important methods that are used with `@see`

**types**
>list~
- small description describing it's purpose
- extended classes using `@see`

**Comment by SirOphis** [comment]
solid and will be implemented in every future pull request!
